### ISSUE TITLE
mini player feature

### ISSUE THREAD

**Issue by Justsnoopy30** [Venipa/ytmdesktop2#17]
May just not be implemented yet though

**Comment by Venipa** [comment]
don't intend to work on a mini player but ill add it to the backlog

**Comment by Justsnoopy30** [comment]
The original Ytmdesktop has some code for this already you could possibly use?

**Comment by GallopingCow** [comment]
I'd just like to show my support for a mini player. I only just discovered your version of the desktop player today, and have up to this point been using the version from https://ytmdesktop.app. I absolutely love the mini player and being able to put it on my second screen at work to admire album art while I do other things.

**Comment by Venipa** [comment]
@GallopingCow @Justsnoopy30 mini player development is in progress

![image](https://user-images.githubusercontent.com/17952364/183205288-abf687ed-7564-4158-859b-c7dad035db8d.png)

**Comment by GallopingCow** [comment]
@Venipa Thank you so much for your time and effort in this!
I've been very frustrated with the original ytmd app lately because my music is constantly pausing and skipping songs at random. I've been assuming it's an issue with system resources, but I don't seem to have the same trouble with this app.

I'd love to see an option for the miniplayer to just show the album art with overlaid song information and playback controls that appear on mouseover. In my opinion, the mini player from the original ytmd app was perfect because I could dedicate a small corner of my screen (or an entire quarter of my second monitor at work) to just showing the album art.
![image](https://user-images.githubusercontent.com/9714175/193298810-2669bddd-cd6f-44a7-9a4a-5c392bc6f266.png)
